#include <windows.h>

bool loadDrv(LPCSTR drvFile);
DWORD64 getBaseModule(HANDLE proc);
void readMem(HANDLE proc, DWORD64 addr, int size, PVOID data);
void writeMem(HANDLE proc, DWORD64 addr, int size, PVOID data);
void protect();

extern char * Service_NAME;

#define IOCTL_IO_MODULE				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1000, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_READ				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_WRITE				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_HIDEDRV			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1003, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_PROTECT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1004, METHOD_IN_DIRECT, FILE_ANY_ACCESS)