#include <windows.h>

bool loadDrv(LPCSTR drvFile);
HANDLE Debug_OpenProcess(HANDLE ProcessID, ULONG Access);
HANDLE Debug_OpenThread(HANDLE ThreadID, ULONG Access);
DWORD64 getBaseModule(HANDLE proc);
void readMem(HANDLE proc, DWORD64 addr, int size, PVOID data);
void writeMem(HANDLE proc, DWORD64 addr, int size, PVOID data);
void protect();
void unloadDrv();

extern char * Service_NAME;
extern HANDLE hDevice;
extern HANDLE hGameProcess;


#define IOCTL_IO_MODULE						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1000, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_READ						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_WRITE						CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_HIDEDRV					CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1003, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_PROTECT					CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1004, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_DEBUG_OPENPROCESS			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1010, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_IO_DEBUG_OPENTHREAD			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1011, METHOD_IN_DIRECT, FILE_ANY_ACCESS)